apiVersion: apps/v1
kind: Deployment
metadata:
  name: karthik-deployment
  labels:
    app: tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: karthub/karthik-tomcat:v1
        ports:
        - containerPort: 80
