From centos:centos7
MAINTAINER karthikk61@gmail.com
Run yum -y update && yum -y install epel-release && yum -y install java-1.8.0-openjdk.x86_64
Run mkdir /opt/tomcat
Run yum install tomcat8
Copy app.war /usr/local/tomat/webapps
Cmd 
